title: Wetter Routing App
description: Dokumentation zur Wetter Routing App
baseurl: "/WetterRoutingApp"
theme: jekyll-theme-cayman
show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
